// Dicionário de campos do ERP Senior (rótulos amigáveis)
// Usado para exibir o "nome real" do campo ao lado do código técnico
// nas telas de SGU › Preview por campo, Comparar usuários, etc.

type FieldMap = Record<string, string>;

// Fallback global — campos comuns que aparecem em várias tabelas Senior (E099*, R910, R999, etc.)
const GLOBAL: FieldMap = {
  // Identificação de usuário
  CODUSU: 'Código do Usuário',
  NOMUSU: 'Nome do Usuário',
  DESUSU: 'Descrição do Usuário',
  NOMCOM: 'Nome Completo',
  TIPUSU: 'Tipo de Usuário',
  BLOUSU: 'Usuário Bloqueado',
  SENHA: 'Senha',
  OBSUSU: 'Observação do Usuário',
  IDEEXT: 'Identificador Externo',

  // Empresa / Filial / Estrutura
  NUMEMP: 'Número da Empresa',
  CODEMP: 'Código da Empresa',
  NUMFIL: 'Número da Filial',
  CODFIL: 'Código da Filial',
  EMPATI: 'Empresa de Atividade',
  FILATI: 'Filial de Atividade',
  PSTATI: 'Posto de Atividade',
  EMPCOL: 'Empresa do Colaborador',
  FILCOL: 'Filial do Colaborador',

  // Colaborador / cadastro
  TIPCOL: 'Tipo de Colaborador',
  NUMCAD: 'Número do Cadastro',
  NOMFUN: 'Nome do Funcionário',
  SITCAD: 'Situação do Cadastro',
  COOCCU: 'Código da Ocupação',
  SUPTME: 'Superior Imediato',
  CARGO: 'Cargo',
  LOTACAO: 'Lotação',

  // Permissão / acesso
  INDPER: 'Indicador de Permissão',
  NIVPER: 'Nível de Permissão',
  INDACE: 'Indicador de Acesso',
  INDPAD: 'Indicador Padrão',
  INDATI: 'Indicador Ativo',
  INDBLO: 'Indicador de Bloqueio',
  INDEXC: 'Indicador de Exclusão',
  INDINC: 'Indicador de Inclusão',
  INDALT: 'Indicador de Alteração',
  INDCON: 'Indicador de Consulta',

  // Datas / auditoria
  DATINI: 'Data Inicial',
  DATFIM: 'Data Final',
  DATALT: 'Data da Alteração',
  HORALT: 'Hora da Alteração',
  USUALT: 'Usuário da Alteração',
  DATCAD: 'Data de Cadastro',
  DATEXC: 'Data de Exclusão',

  // Financeiro
  CODFPG: 'Forma de Pagamento',
  FPGOBR: 'Forma de Pagamento Obrigatória',
  CODTPT: 'Tipo de Título',
  CODNAT: 'Natureza',
  CODCCU: 'Código do Centro de Custo',
  CODPRJ: 'Código do Projeto',
  CODFOR: 'Código do Fornecedor',
  CODCLI: 'Código do Cliente',
  CODCFO: 'Cliente / Fornecedor',
  CODESP: 'Espécie',
  CODBAN: 'Banco',
  CODCCO: 'Conta Corrente',
  CODFCO: 'Filial da Conta',
  CODAGE: 'Agência',
  CODMOE: 'Moeda',

  // Estrutura organizacional
  CODGRP: 'Grupo',
  CODDEP: 'Departamento',
  CODSEC: 'Seção',
  CODVEN: 'Vendedor',
  CODCPR: 'Comprador',
  CODREP: 'Representante',
  CODTRA: 'Transportadora',
  CODOPR: 'Operador',
  CODORI: 'Origem',

  // Dados pessoais
  ESTCIV: 'Estado Civil',
  GRAINS: 'Grau de Instrução',
  NACFUN: 'Nacionalidade',
  SEXFUN: 'Sexo',
  CORRAC: 'Cor / Raça',
  DATNAS: 'Data de Nascimento',
  NUMCPF: 'CPF',
  NUMRGE: 'RG',
  NUMPIS: 'PIS / PASEP',
  CARTRA: 'Carteira de Trabalho',

  // Endereço / contato
  TIPLOG: 'Tipo de Logradouro',
  ENDRUA: 'Endereço',
  NUMEND: 'Número do Endereço',
  CPLEND: 'Complemento',
  BAIRES: 'Bairro',
  CIDRES: 'Cidade',
  ESTRES: 'UF',
  CEPRES: 'CEP',
  TELRES: 'Telefone Residencial',
  TELCEL: 'Celular',
  INTNET: 'E-mail (Internet)',
  GERAUS: 'Gera Usuário (S/N)',

  // Flags de acesso e perfil
  INDADM: 'Indicador Administrador',
  INDMAS: 'Usuário Mestre',
  INDLOG: 'Permite Login',
  INDWEB: 'Acesso Web',
  INDAPP: 'Acesso App',
  INDREL: 'Acesso a Relatórios',
  INDEXP: 'Permite Exportação',
  INDLAN: 'Permite Lançamento',
  INDAPR: 'Indicador Aprovador',
  NIVACE: 'Nível de Acesso',

  // Limites e moeda
  LIMAPR: 'Limite de Aprovação',
  LIMVAL: 'Limite de Valor',
  LIMVEN: 'Limite de Venda',
  DESMAX: 'Desconto Máximo (%)',
  MOEAPR: 'Moeda do Limite',
  MOEVEN: 'Moeda da Venda',

  // Senha / sessão
  DATEXP: 'Data de Expiração',
  DIAEXP: 'Dias para Expiração de Senha',
  INDSEN: 'Troca de Senha Obrigatória',
  TENINV: 'Tentativas Inválidas',
  LIBHOR: 'Libera fora de Horário',
  IDIUSU: 'Idioma do Usuário',
};

// Mapas específicos por tabela (sobrepõem o GLOBAL quando houver)
const BY_TABLE: Record<string, FieldMap> = {
  // ===== R910 / R999 — Cadastro base de usuários =====
  R910USU: {},
  R999USU: {
    NOMUSU: 'Nome do Usuário',
    CODUSU: 'Código do Usuário',
    SITCAD: 'Situação do Cadastro',
    SENHA: 'Senha',
    BLOUSU: 'Usuário Bloqueado',
  },

  // ===== E099USU — Parâmetros gerais do usuário SGU =====
  E099USU: {
    CODUSU: 'Código do Usuário',
    NUMEMP: 'Número da Empresa',
    TIPUSU: 'Tipo de Usuário',
    INDPAD: 'Empresa Padrão',
    INDACE: 'Indicador de Acesso',
    NIVACE: 'Nível de Acesso',
    TIPCOL: 'Tipo de Colaborador',
    NUMCAD: 'Cadastro do Colaborador',
    EMPATI: 'Empresa de Atividade',
    FILATI: 'Filial de Atividade',
    PSTATI: 'Posto de Atividade',
    INDADM: 'Indicador Administrador',
    INDMAS: 'Usuário Mestre',
    INDLOG: 'Permite Login',
    INDWEB: 'Acesso Web',
    INDAPP: 'Acesso App',
    INDREL: 'Acesso a Relatórios',
    INDEXP: 'Permite Exportação',
    DATEXP: 'Data de Expiração',
    DIAEXP: 'Dias para Expiração de Senha',
    INDSEN: 'Troca de Senha Obrigatória',
    TENINV: 'Tentativas Inválidas',
    LIBHOR: 'Libera fora de Horário',
    IDIUSU: 'Idioma do Usuário',
    VENTBP: 'Vendedor Padrão (TBP)',
    CODFIL: 'Filial Padrão',
    CODDEP: 'Departamento Padrão',
    CODSEC: 'Seção Padrão',
    CODCCU: 'Centro de Custo Padrão',
    CODPRJ: 'Projeto Padrão',
    CODCPR: 'Comprador Padrão',
    CODVEN: 'Vendedor Padrão',
    CODREP: 'Representante Padrão',
    CODTRA: 'Transportadora Padrão',
    CODOPR: 'Operador Padrão',
    SUPIME: 'Superior Imediato',
    GERAUS: 'Gera Usuário (S/N)',
    FPGOBR: 'Forma de Pagamento Obrigatória',
    INTNET: 'E-mail (Internet)',
    SITUSU: 'Situação do Usuário',
    CODMOT: 'Código do Motivo',
    OBSMOT: 'Observação do Motivo',
    USUMOT: 'Usuário do Motivo',
    DATMOT: 'Data do Motivo',
    HORMOT: 'Hora do Motivo',
    USUGER: 'Usuário Geração',
    DATGER: 'Data Geração',
    HORGER: 'Hora Geração',
    USUALT: 'Usuário Alteração',
    DATALT: 'Data Alteração',
    HORALT: 'Hora Alteração',
    DATSIN: 'Data da Sincronização',
    HORSIN: 'Hora da Sincronização',
    CODCLI: 'Código do Cliente',
    CODFOR: 'Código do Fornecedor',
    CODPOR: 'Porta de Comunicação',
    NOMSER: 'Nome do Servidor',
    PORSER: 'Porta do Servidor',
    AUTUSU: 'Autenticação Adicional',
    USUAUT: 'Usuário Autenticador',
    SENAUT: 'Senha Autenticador',
    MLTLGN: 'Permite Múltiplo Login',
    MAXLGN: 'Máximo de Logins Simultâneos',
    TURTRB: 'Turno de Trabalho',
    CODCEL: 'Código da Célula',
    REPVAR: 'Repete Variável',
    PERFPC: 'Permite Forma de Pagamento Customizada',

    // Vendas (VEN*)
    VENNSP: 'Vendas — Não Sugere Preço',
    VENPAR: 'Vendas — Permite Alterar Rateio',
    VENPAP: 'Vendas — Permite Alterar Preço',
    VENPDS: 'Vendas — Permite Alterar Desconto',
    VENPIP: 'Vendas — Permite Alterar IPI',
    VENPIC: 'Vendas — Permite Alterar ICMS',
    VENPCO: 'Vendas — Permite Alterar Comissão',
    VENPIS: 'Vendas — Permite Alterar PIS',
    VENPIR: 'Vendas — Permite Alterar IR',
    VENPIN: 'Vendas — Permite Alterar INSS',
    VENPFU: 'Vendas — Permite Alterar Frete Unitário',
    VENAUN: 'Vendas — Altera Unidade',
    VENATP: 'Vendas — Altera Tipo de Pedido',
    VENACL: 'Vendas — Altera Cliente',
    VENARE: 'Vendas — Altera Representante',
    VENASP: 'Vendas — Altera Situação do Pedido',
    VENLPD: 'Vendas — Libera Preço Diferenciado',
    VENACV: 'Vendas — Altera Condição de Venda',
    VENANS: 'Vendas — Altera NF de Saída',
    VENLNS: 'Vendas — Libera NF de Saída',
    VENASR: 'Vendas — Altera Série',
    VENRAT: 'Vendas — Permite Rateio',
    VENPAE: 'Vendas — Pedido em Aberto',
    VENADG: 'Vendas — Altera Desconto Geral',
    VENAPI: 'Vendas — Altera Pedido Importado',
    VENFQP: 'Vendas — Forma de Quitação Padrão',
    VENPOF: 'Vendas — Permite Oferta',
    VENPTN: 'Vendas — Permite Troca de Natureza',
    VENPCA: 'Vendas — Permite Cancelamento',
    VENPCD: 'Vendas — Permite Cadastro',
    VENPSE: 'Vendas — Permite Seleção',
    VENPFP: 'Vendas — Permite Forma de Pagamento',
    VENLPV: 'Vendas — Libera Pedido Venda',
    VENLPF: 'Vendas — Libera Preço Final',
    VENLPC: 'Vendas — Libera Preço de Custo',
    VENLPP: 'Vendas — Libera Preço Promocional',
    VENLPI: 'Vendas — Libera Preço Item',
    VENLPA: 'Vendas — Libera Preço Adicional',
    VENLCE: 'Vendas — Libera Cálculo Especial',
    VENATV: 'Vendas — Altera Tabela de Vendas',
    VENATF: 'Vendas — Altera Tabela de Frete',
    VENAVA: 'Vendas — Altera Validade',
    VENAIR: 'Vendas — Altera IRRF',
    VENASE: 'Vendas — Altera Série',
    VENIFC: 'Vendas — Inclui Frete Calculado',
    VENCST: 'Vendas — Custo do Item',
    VENCNS: 'Vendas — Cancela NF de Saída',
    VENRNS: 'Vendas — Reverte NF de Saída',
    VENSCV: 'Vendas — Status Condição de Venda',
    VENSDG: 'Vendas — Status Desconto Geral',
    VENSPP: 'Vendas — Status Preço Promocional',
    VENCNP: 'Vendas — Cancela Pedido',
    VENCPD: 'Vendas — Cancela Pedido',
    VENRPD: 'Vendas — Reverte Pedido',

    // Compras (CPR*)
    CPRMAC: 'Compras — Máximo Aprovação',
    CPRMOC: 'Compras — Máximo OC',
    CPRPAP: 'Compras — Permite Alterar Preço',
    CPRPDS: 'Compras — Permite Alterar Desconto',
    CPRPIP: 'Compras — Permite Alterar IPI',
    CPRPIC: 'Compras — Permite Alterar ICMS',
    CPRPIS: 'Compras — Permite Alterar PIS',
    CPRPIR: 'Compras — Permite Alterar IR',
    CPRPIN: 'Compras — Permite Alterar INSS',
    CPRPFU: 'Compras — Permite Alterar Frete Unitário',
    CPRVNO: 'Compras — Variação Negociação',
    CPRQNO: 'Compras — Quantidade Negociação',
    CPRVDN: 'Compras — Valor Desconto Negociação',
    CPRPDN: 'Compras — Percentual Desconto Negociação',
    CPRAPD: 'Compras — Aprova Pedido',
    CPRAFO: 'Compras — Aprova Fornecedor',
    CPRAOC: 'Compras — Aprova OC',
    CPRACC: 'Compras — Aprova Centro Custo',
    CPRANE: 'Compras — Aprova Natureza',
    CPRRAT: 'Compras — Permite Rateio',
    CPRADG: 'Compras — Aprova Desconto Geral',
    CPRACF: 'Compras — Aprova Conta Fiscal',
    CPRATX: 'Compras — Aprova Taxa',
    CPRAHF: 'Compras — Aprova Horário Fora',
    CPRAPI: 'Compras — Aprova Pedido Importado',
    CPRPQT: 'Compras — Permite Alterar Quantidade',
    CPRPSC: 'Compras — Permite Solicitação Compra',
    CPRPEC: 'Compras — Permite Escolha Cotação',
    CPRPOS: 'Compras — Permite Ordem de Serviço',
    CPRPSE: 'Compras — Permite Seleção',
    CPRFOC: 'Compras — Forma OC',
    CPRFCP: 'Compras — Forma Compra',
    CPRFPO: 'Compras — Forma Pedido OC',
    CPRSCC: 'Compras — Solicita Centro Custo',
    CPRRCA: 'Compras — Replica Cabeçalho',
    CPRIGC: 'Compras — Ignora Conferência',
    CPRASC: 'Compras — Aprova Solicitação Compra',
    CPRAQC: 'Compras — Aprova Quadro Comparativo',
    CPRBLO: 'Compras — Bloqueia',
    CPRCST: 'Compras — Custo do Item',

    // Estoque (EST*)
    ESTAES: 'Estoque — Altera Empresa',
    ESTRAT: 'Estoque — Permite Rateio',
    ESTPLP: 'Estoque — Plano Logístico Padrão',
    ESTGSA: 'Estoque — Gerencia Saldo',
    ESTADR: 'Estoque — Altera Endereço',
    ESTAGC: 'Estoque — Altera Grupo Custo',

    // Receber (REC*)
    RECPGR: 'Receber — Pago/Geral',
    RECAVR: 'Receber — Avulso',
    RECAVL: 'Receber — Avulso Liberado',
    RECRAT: 'Receber — Rateio',
    RECARF: 'Receber — Altera Forma Recebimento',
    RECACD: 'Receber — Altera Condição',

    // Pagar (PAG*)
    PAGMAX: 'Pagar — Valor Máximo',
    PAGPGR: 'Pagar — Pago/Geral',
    PAGAVP: 'Pagar — Avulso Pago',
    PAGAVL: 'Pagar — Avulso Liberado',
    PAGEEV: 'Pagar — Evento',
    PAGRAT: 'Pagar — Rateio',
    PAGARF: 'Pagar — Altera Forma Pagamento',
    PAGACD: 'Pagar — Altera Condição',
    PAGDET: 'Pagar — Detalhamento',

    // Caixa/Bancos (CXB*)
    CXBDCP: 'Caixa/Bancos — Dias para Pagamento',
    CXBAPM: 'Caixa/Bancos — Aprova Movimentação',
    CXBRAT: 'Caixa/Bancos — Rateio',
    CXBARF: 'Caixa/Bancos — Altera Forma',
    CXBPGP: 'Caixa/Bancos — Pagamento Programado',

    // Contabilidade (CTB*)
    CTBDAC: 'Contabilidade — Direção Acesso',
    CTBALT: 'Contabilidade — Altera Lançamento',
    CTBCLT: 'Contabilidade — Cancela Lançamento',
    CTBALC: 'Contabilidade — Altera Lote',
    CTBCLC: 'Contabilidade — Cancela Lote',
    CTBART: 'Contabilidade — Altera Roteiro',
    CTBCRT: 'Contabilidade — Cancela Roteiro',
    CTBAOR: 'Contabilidade — Altera Origem',
    CTBCOR: 'Contabilidade — Cancela Origem',
    CTBACT: 'Contabilidade — Altera Conta',
    CTBAHP: 'Contabilidade — Altera Histórico Padrão',
    CTBACF: 'Contabilidade — Altera Conta Fiscal',
    CTBLFL: 'Contabilidade — Libera Lançamento',
    CTBZER: 'Contabilidade — Permite Zerar',
    CTBELT: 'Contabilidade — Exclui Lançamento',
    CTBELC: 'Contabilidade — Exclui Lote',
    CTBLTC: 'Contabilidade — Lançamento Técnico',

    // Produção (PRD*)
    PRDDPA: 'Produção — Dias Programação Anterior',
    PRDDPP: 'Produção — Dias Programação Posterior',
    PRDEPB: 'Produção — Edita Programação Base',
    PRDOPD: 'Produção — Operação Padrão',
    OPDORP: 'Operação Origem Padrão',

    // Ativos (AST*)
    ASTORP: 'Ativos — Origem Padrão',
    ASTSOR: 'Ativos — Sem Origem',
    ASTNFV: 'Ativos — NF Venda',
    ASTPED: 'Ativos — Pedido',
    ASTPSI: 'Ativos — Permite Sem Item',
    ASTETO: 'Ativos — Estorno',

    // Movimentação Custos (MPC*)
    MPCACT: 'Mov. Custos — Altera Custo Total',
    MPCACF: 'Mov. Custos — Altera Custo Final',
    MPCACC: 'Mov. Custos — Altera Custo Contábil',
    MPCACA: 'Mov. Custos — Altera Custo Apropriado',

    // Aprovação (APR*)
    APRDFT: 'Aprovação — Default',
    APRDOC: 'Aprovação — Documento',
    APRSCT: 'Aprovação — Sem Contrato',

    // Indicadores
    INDANT: 'Indicador Antecipação',
    INDPON: 'Indicador Ponto',
    INDQGO: 'Indicador Quadro de Gestão',
    INDAST: 'Indicador Ativos',
    INDMRE: 'Indicador Margem Receita',

    // Patrimônio
    PATDFL: 'Patrimônio — Default',
    PATEMP: 'Patrimônio — Empresa',
    PATTDE: 'Patrimônio — Tipo Despesa',

    // Distribuição
    DISRRA: 'Distribuição Rateio Receita',
    DISINR: 'Distribuição Inicial Rateio',
    DISENR: 'Distribuição Encerramento Rateio',

    // Projetos
    PRJLFD: 'Projeto — Libera Fim',
    PRJNUS: 'Projeto — Novo Usuário',
    PRJTSO: 'Projeto — Tem Sócio',

    // Permissões diversas
    ACRCCM: 'Acréscimo Centro Custo Manual',
    PEREXS: 'Permite Extrair Saída',
    PERACF: 'Permite Acesso Conta Fiscal',
    PERUNI: 'Permite Unidade',
    PERCNL: 'Permite Cancelar',
    USUCFE: 'Usuário CF-e',
    CONQAR: 'Conferência Quadro Aprovação',
    CONREC: 'Conciliação Recebimento',
    CONAGE: 'Conciliação Agência',
    MANAGE: 'Manutenção Agência',
    CPOCPF: 'Campo CPF',
    CLEQTD: 'Cliente — Quantidade',
    CLEPRC: 'Cliente — Preço',
    COBPDJ: 'Cobrança PDJ',
    COBATC: 'Cobrança Automática',

    // Alterações
    ALTREM: 'Altera Remessa',
    ALTMON: 'Altera Moeda',
    ALTEBQ: 'Altera Empresa/Banco',
    ALTINP: 'Altera Inadimplência',
    ALTNNU: 'Altera Número/Numeração',

    // Auditoria
    AUDPFA: 'Auditoria Pré-Financeiro',
    SENAPR: 'Senha Aprovador',

    // Outros
    SIMFEC: 'Simula Fechamento',
    EXAOCP: 'Executa Operação Compra',
    PRPOCP: 'Programa Operação Compra',
    REBNFI: 'Rebimento NF Importação',
    IMPRAT: 'Imprime Rateio',
    PARESP: 'Parâmetro Especial',
    CANNFE: 'Cancela NF-e',
    DATAFI: 'Data Final',
    USU_APRQUAL: 'Aprovador Qualidade',

    // Observações Móveis
    OBSMOB: 'Observação Móvel — Bloqueio',
    OBSMOL: 'Observação Móvel — Liberação',
    OBSMOR: 'Observação Móvel — Reabertura',

    // Diretórios
    DIRCTE: 'Diretório CT-e',
    DIRNES: 'Diretório NF-e Saída',
    DIRNEL: 'Diretório NF-e Leitura',
    DIRMDF: 'Diretório MDF-e',
  },

  // ===== E099CPR — Compradores autorizados =====
  E099CPR: {
    CODUSU: 'Código do Usuário',
    NUMEMP: 'Número da Empresa',
    CODCPR: 'Comprador Autorizado',
    INDPAD: 'Comprador Padrão',
    INDACE: 'Indicador de Acesso',
    INDAPR: 'Aprovador',
    LIMAPR: 'Limite de Aprovação',
    MOEAPR: 'Moeda do Limite',
    DEMITR: 'Comprador Demitido',
    ALTCTR: 'Altera Contrato',
    ALTPDT: 'Altera Pedido',
    AUTMDE: 'Autoriza Modo Direto Empresa',
    PERAGR: 'Permite Agrupamento',
  },

  // ===== E099FIN — Restrições financeiras =====
  E099FIN: {
    CODUSU: 'Código do Usuário',
    NUMEMP: 'Número da Empresa',
    CODFPG: 'Forma de Pagamento',
    CODTPT: 'Tipo de Título',
    CODNAT: 'Natureza Financeira',
    CODCCU: 'Centro de Custo',
    CODPRJ: 'Projeto',
    CODESP: 'Espécie',
    CODFOR: 'Fornecedor',
    CODCLI: 'Cliente',
    CODCFO: 'Cliente / Fornecedor',
    CODBAN: 'Banco',
    CODCCO: 'Conta Corrente',
    CODFCO: 'Filial da Conta',
    INDACE: 'Indicador de Acesso',
    INDPAD: 'Padrão',
    LIMVAL: 'Limite de Valor',
    PAGALT: 'Pagar — Tipo de Alteração',
    PAGABA: 'Pagar — Altera Abatimento',
    PAGAJR: 'Pagar — Altera Juros',
    PAGAML: 'Pagar — Altera Multa',
    PAGAEN: 'Pagar — Altera Encargos',
    PAGACR: 'Pagar — Altera Acréscimo',
    PAGAAC: 'Pagar — Altera Acordo',
    PAGASC: 'Pagar — Altera Saldo Cobrança',
    PAGADE: 'Pagar — Altera Desconto',
    PAGALQ: 'Pagar — Altera Alíquota',
    PAGMOE: 'Pagar — Altera Moeda',
    RECABA: 'Receber — Altera Abatimento',
    RECAJR: 'Receber — Altera Juros',
    RECAML: 'Receber — Altera Multa',
    RECAEN: 'Receber — Altera Encargos',
    RECACR: 'Receber — Altera Acréscimo',
    RECAAC: 'Receber — Altera Acordo',
    RECASC: 'Receber — Altera Saldo Cobrança',
    RECADE: 'Receber — Altera Desconto',
    RECALQ: 'Receber — Altera Alíquota',
    RECMOE: 'Receber — Altera Moeda',
    PERGDS: 'Permite Gerar Desconto',
    CXBBLO: 'Bloqueia Caixa/Banco',
    MAIPAR: 'Maior Parcial',
    ENTREN: 'Entrada/Renegociação',
    BAIPER: 'Baixa Permitida',
    MOVLOJ: 'Movimentação Loja',
  },

  // ===== E099GCO — Grupos de contas =====
  E099GCO: {
    CODUSU: 'Código do Usuário',
    NUMEMP: 'Número da Empresa',
    CODGRP: 'Código do Grupo',
    CODCCU: 'Centro de Custo',
    CODPRJ: 'Projeto',
    INDACE: 'Indicador de Acesso',
    INDPAD: 'Grupo Padrão',
    NIVPER: 'Nível de Permissão',
    CONACE: 'Conta com Acesso',
    USUGER: 'Usuário Geração',
    DATGER: 'Data Geração',
    HORGER: 'Hora Geração',
  },

  // ===== E099UCP — Usuário × Centro de Custo / Projeto =====
  E099UCP: {
    CODUSU: 'Código do Usuário',
    NUMEMP: 'Número da Empresa',
    CODCCU: 'Centro de Custo',
    CODPRJ: 'Projeto',
    INDACE: 'Indicador de Acesso',
    INDPAD: 'Centro de Custo Padrão',
    NIVPER: 'Nível de Permissão',
    DATINI: 'Data Inicial',
    DATFIM: 'Data Final',
    INDLAN: 'Permite Lançamento',
    INDCON: 'Permite Consulta',
    ALTTCP: 'Altera Tipo CC/Projeto',
    OPCCTR: 'Opção de Contrato',
    USUGER: 'Usuário Geração',
    DATGER: 'Data Geração',
    HORGER: 'Hora Geração',
    REPFIX: 'Repete Fixo',
    ACEHRY: 'Aceita Hierarquia',
  },

  // ===== E099UDE — Usuário × Departamento =====
  E099UDE: {
    CODUSU: 'Código do Usuário',
    NUMEMP: 'Número da Empresa',
    CODDEP: 'Departamento',
    CODSEC: 'Seção',
    INDACE: 'Indicador de Acesso',
    INDPAD: 'Departamento Padrão',
    NIVPER: 'Nível de Permissão',
    DATINI: 'Data Inicial',
    DATFIM: 'Data Final',
    DBUNFE: 'Débito NF Entrada',
    DBUNFS: 'Débito NF Saída',
    DBUCTE: 'Débito Conta Específica',
    USUGER: 'Usuário Geração',
    DATGER: 'Data Geração',
    HORGER: 'Hora Geração',
  },

  // ===== E099USE — Usuário × Seção / Empresa =====
  E099USE: {
    CODUSU: 'Código do Usuário',
    NUMEMP: 'Número da Empresa',
    NUMFIL: 'Número da Filial',
    CODSEC: 'Seção',
    INDACE: 'Indicador de Acesso',
    INDPAD: 'Empresa Padrão',
    EMPATI: 'Empresa de Atividade',
    FILATI: 'Filial de Atividade',
    DATINI: 'Data Inicial',
    DATFIM: 'Data Final',
    DESXTD: 'Descrição Estendida',
  },

  // ===== E099UVE — Usuário × Vendedor =====
  E099UVE: {
    CODUSU: 'Código do Usuário',
    NUMEMP: 'Número da Empresa',
    CODVEN: 'Vendedor Autorizado',
    INDPAD: 'Vendedor Padrão',
    INDACE: 'Indicador de Acesso',
    LIMVEN: 'Limite de Venda',
    DESMAX: 'Desconto Máximo (%)',
    MOEVEN: 'Moeda da Venda',
    ALTTVE: 'Altera Tipo de Vendedor',
    PEREPS: 'Permite Empresa Personalizada',
    USUGER: 'Usuário Geração',
    DATGER: 'Data Geração',
    HORGER: 'Hora Geração',
    CODAGR: 'Código de Agregação',
    ENVRSG: 'Envia Resgate',
  },
};

/**
 * Retorna o rótulo amigável de um campo do ERP.
 * Tenta primeiro o mapa específico da tabela, depois o fallback global.
 * Se não houver mapeamento, retorna o próprio código no formato `(TABELA.CAMPO)`
 * para que campos não mapeados fiquem visíveis e possam ser reportados.
 */
export function getFieldLabel(
  tabela: string | null | undefined,
  campo: string | null | undefined,
): string {
  if (!campo) return '—';
  const tab = (tabela ?? '').toUpperCase();
  const key = campo.toUpperCase();
  const tabMap = BY_TABLE[tab];
  return tabMap?.[key] ?? GLOBAL[key] ?? `(${tab || '?'}.${key})`;
}
