project_id = "cpgyhjqufxeweyswosuw"

[functions.ai-assistant]
verify_jwt = false

[functions.sugestao-minmax-ia]
verify_jwt = false

[functions.azure-auth-start]
verify_jwt = false

[functions.azure-auth-callback]
verify_jwt = false
