// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to verify the connection is working.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-passagens-aereas.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_passagens_aereas_default = defineTool2({
  name: "list_passagens_aereas",
  title: "List air travel records",
  description: "List recent air travel (passagens a\xE9reas) records for the signed-in user, honoring row-level security. Supports simple filters and a row limit.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50).describe("Maximum number of rows to return (1-200)."),
    colaborador: z2.string().trim().optional().describe("Optional case-insensitive substring to filter by collaborator name."),
    since: z2.string().optional().describe(
      "Optional ISO date (YYYY-MM-DD). Only records with data_registro >= this date are returned."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, colaborador, since }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    let query = supabaseForUser(ctx).from("passagens_aereas").select("*").order("data_registro", { ascending: false }).limit(limit);
    if (colaborador) query = query.ilike("colaborador", `%${colaborador}%`);
    if (since) query = query.gte("data_registro", since);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Returned ${data?.length ?? 0} record(s).`
        }
      ],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cpgyhjqufxeweyswosuw";
var mcp_default = defineMcp({
  name: "sapiens-erp-mcp",
  title: "HUB de Gest\xE3o",
  version: "0.1.0",
  instructions: "Tools for the HUB de Gest\xE3o. Use `echo` to verify connectivity, and `list_passagens_aereas` to read air travel records for the signed-in user (respects row-level security).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_passagens_aereas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
