CREATE TABLE IF NOT EXISTS public.producao_recurso_unidade (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codemp INTEGER NOT NULL,
  codcre TEXT NOT NULL,
  descre TEXT,
  unidade_negocio TEXT NOT NULL,
  tipo_recurso TEXT,
  codccu_sugerido TEXT,
  considera_carga BOOLEAN NOT NULL DEFAULT TRUE,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  obs TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (codemp, codcre)
);

CREATE INDEX IF NOT EXISTS idx_producao_recurso_unidade_codemp ON public.producao_recurso_unidade (codemp);
CREATE INDEX IF NOT EXISTS idx_producao_recurso_unidade_codcre ON public.producao_recurso_unidade (codcre);
CREATE INDEX IF NOT EXISTS idx_producao_recurso_unidade_unidade ON public.producao_recurso_unidade (unidade_negocio);
CREATE INDEX IF NOT EXISTS idx_producao_recurso_unidade_ativo ON public.producao_recurso_unidade (ativo);

ALTER TABLE public.producao_recurso_unidade ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated read producao_recurso_unidade"
  ON public.producao_recurso_unidade FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "Admins manage producao_recurso_unidade"
  ON public.producao_recurso_unidade FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

CREATE TRIGGER trg_producao_recurso_unidade_updated_at
  BEFORE UPDATE ON public.producao_recurso_unidade
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();